FROM ubuntu:14.04

# Install Ansible
RUN apt-get update && apt-get install -y \
    software-properties-common \
 && apt-add-repository -y ppa:ansible/ansible \
 && apt-get update && apt-get install -y \
    ansible \
    git \
 && rm -rf /var/lib/apt/lists/*

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
